import i18next from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  en: {
    translation: {
      welcome: "Welcome to AgroAI",
      cropRecommendation: "Crop Recommendation",
      diseaseDetection: "Disease Detection",
      weather: "Weather",
      takePhoto: "Take Photo",
      selectLanguage: "Select Your Language",
      continue: "Continue",
      login: "Login",
      register: "Register",
      welcomeBack: "Welcome Back!",
      loginToContinue: "Login to your account to continue",
      mobileNumber: "Mobile Number",
      createAccount: "Create a New Account",
      farmDetails: "Enter your details to get started",
      name: "Name",
      acresOfLand: "Acres of Land",
      areaOfLand: "Area of Land (e.g., Village, City)",
      gallery: "Gallery",
      analyzing: "Analyzing...",
      healthy: "Healthy",
      treatment: "Treatment",
      error: "Error",
      success: "Success",
      fillAllFields: "Please fill all the fields.",
      invalidMobile: "Please enter a valid 10-digit mobile number.",
      accountCreated: "Account created successfully! You are now logged in.",
      accountCreateFailed: "Failed to create account. Please try again.",
      welcomeBackUser: "Welcome back, {{name}}!",
      noAccountFound: "No account found with this mobile number. Please register.",
      alreadyHaveAccount: "Already have an account?",
      dontHaveAccount: "Don't have an account?",
      goBack: "Go Back",
      changeLanguage: "Change Language",
      smartFarmingAssistant: "Your Smart Farming Assistant",
      continueBoth: "Continue / जारी रखें",
      permissionDenied: "Permission Denied",
      locationPermission: "Location access is needed to provide localized weather and advice.",
      micPermission: "Microphone access is needed for the voice assistant feature.",
      recommendationError: "Failed to get recommendations",
      captureError: "Failed to capture image",
      selectImageError: "Failed to select image",
      analyzeError: "Failed to analyze image",
      weatherError: "Failed to fetch weather data",
      voiceDemoError: "Voice recognition not available in this demo",
      initError: "Failed to initialize the app. Please restart.",
      // Add more translations as needed
    }
  },
  hi: {
    translation: {
      welcome: "एग्रोएआई में आपका स्वागत है",
      cropRecommendation: "फसल सिफारिश",
      diseaseDetection: "रोग की पहचान",
      weather: "मौसम",
      selectLanguage: "अपनी भाषा चुनें",
      continue: "जारी रखें",
      login: "लॉग इन करें",
      register: "पंजीकरण करें",
      welcomeBack: "वापसी पर स्वागत है!",
      loginToContinue: "जारी रखने के लिए अपने खाते में लॉगिन करें",
      mobileNumber: "मोबाइल नंबर",
      createAccount: "एक नया खाता बनाएँ",
      farmDetails: "शुरू करने के लिए अपना विवरण दर्ज करें",
      name: "नाम",
      acresOfLand: "भूमि का एकड़",
      areaOfLand: "भूमि का क्षेत्र (जैसे, गांव, शहर)",
      takePhoto: "फोटो लें",
      gallery: "गैलरी",
      analyzing: "विश्लेषण हो रहा है...",
      healthy: "स्वस्थ",
      treatment: "उपचार",
      error: "त्रुटि",
      success: "सफलता",
      fillAllFields: "कृपया सभी फ़ील्ड भरें।",
      invalidMobile: "कृपया एक मान्य 10-अंकीय मोबाइल नंबर दर्ज करें।",
      accountCreated: "खाता सफलतापूर्वक बनाया गया! अब आप लॉग इन हैं।",
      accountCreateFailed: "खाता बनाने में विफल। कृपया पुनः प्रयास करें।",
      welcomeBackUser: "वापसी पर स्वागत है, {{name}}!",
      noAccountFound: "इस मोबाइल नंबर से कोई खाता नहीं मिला। कृपया पंजीकरण करें।",
      alreadyHaveAccount: "पहले से ही एक खाता है?",
      dontHaveAccount: "खाता नहीं है?",
      goBack: "वापस जाओ",
      changeLanguage: "भाषा बदलें",
      smartFarmingAssistant: "आपका स्मार्ट खेती सहायक",
      continueBoth: "Continue / जारी रखें",
      permissionDenied: "अनुमति अस्वीकृत",
      locationPermission: "स्थानीय मौसम और सलाह प्रदान करने के लिए स्थान की पहुंच आवश्यक है।",
      micPermission: "वॉयस असिस्टेंट सुविधा के लिए माइक्रोफोन की पहुंच आवश्यक है।",
      recommendationError: "सिफारिशें प्राप्त करने में विफल",
      captureError: "छवि कैप्चर करने में विफल",
      selectImageError: "छवि का चयन करने में विफल",
      analyzeError: "छवि का विश्लेषण करने में विफल",
      weatherError: "मौसम डेटा लाने में विफल",
      voiceDemoError: "इस डेमो में आवाज पहचान उपलब्ध नहीं है",
      initError: "ऐप को प्रारंभ करने में विफल। कृपया पुनरारंभ करें।",
    }
  },
  te: {
    translation: {
      welcome: "ఆగ్రోఏఐకి స్వాగతం",
      cropRecommendation: "పంట సిఫార్సు",
      diseaseDetection: "వ్యాధి నిర్ధారణ",
      weather: "వాతావరణం",
      takePhoto: "ఫోటో తీయండి",
      selectLanguage: "మీ భాషను ఎంచుకోండి",
      continue: "కొనసాగించు",
      login: "లాగిన్",
      register: "నమోదు చేసుకోండి",
      welcomeBack: "తిరిగి స్వాగతం!",
      loginToContinue: "కొనసాగించడానికి మీ ఖాతాకు లాగిన్ చేయండి",
      mobileNumber: "మొబైల్ నంబర్",
      createAccount: "కొత్త ఖాతాను సృష్టించండి",
      farmDetails: "ప్రారంభించడానికి మీ వివరాలను నమోదు చేయండి",
      name: "పేరు",
      acresOfLand: "భూమి ఎకరాలు",
      areaOfLand: "భూమి యొక్క ప్రాంతం (ఉదా., గ్రామం, నగరం)",
      gallery: "గ్యాలరీ",
      analyzing: "విశ్లేషిస్తోంది...",
      healthy: "ఆరోగ్యకరమైనది",
      treatment: "చికిత్స",
      error: "లోపం",
      success: "విజయం",
      fillAllFields: "దయచేసి అన్ని ఫీల్డ్‌లను పూరించండి.",
      invalidMobile: "దయచేసి సరైన 10-అంకెల మొబైల్ నంబర్‌ను నమోదు చేయండి.",
      accountCreated: "ఖాతా విజయవంతంగా సృష్టించబడింది! మీరు ఇప్పుడు లాగిన్ అయ్యారు.",
      accountCreateFailed: "ఖాతాను సృష్టించడంలో విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి.",
      welcomeBackUser: "తిరిగి స్వాగతం, {{name}}!",
      noAccountFound: "ఈ మొబైల్ నంబర్‌తో ఖాతా కనుగొనబడలేదు. దయచేసి నమోదు చేసుకోండి.",
      alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా?",
      dontHaveAccount: "ఖాతా లేదా?",
      goBack: "వెనుకకు వెళ్ళు",
      changeLanguage: "భాషను మార్చండి",
      smartFarmingAssistant: "మీ స్మార్ట్ వ్యవసాయ సహాయకుడు",
      continueBoth: "Continue / కొనసాగించు",
      permissionDenied: "అనుమతి నిరాకరించబడింది",
      locationPermission: "స్థానికీకరించిన వాతావరణం మరియు సలహాలను అందించడానికి లొకేషన్ యాక్సెస్ అవసరం.",
      micPermission: "వాయిస్ అసిస్టెంట్ ఫీచర్ కోసం మైక్రోఫోన్ యాక్సెస్ అవసరం.",
      recommendationError: "సిఫార్సులను పొందడంలో విఫలమైంది",
      captureError: "చిత్రాన్ని క్యాప్చర్ చేయడంలో విఫలమైంది",
      selectImageError: "చిత్రాన్ని ఎంచుకోవడంలో విఫలమైంది",
      analyzeError: "చిత్రాన్ని విశ్లేషించడంలో విఫలమైంది",
      weatherError: "వాతావరణ డేటాను పొందడంలో విఫలమైంది",
      voiceDemoError: "ఈ డెమోలో వాయిస్ రికగ్నిషన్ అందుబాటులో లేదు",
      initError: "యాప్‌ను ప్రారంభించడంలో విఫలమైంది. దయచేసి పునఃప్రారంభించండి.",
    }
  },
  ta: {
    translation: {
      welcome: "அக்ரோஏஐ-க்கு வரவேற்கிறோம்",
      cropRecommendation: "பயிர் பரிந்துரை",
      diseaseDetection: "நோய் கண்டறிதல்",
      weather: "வானிலை",
      takePhoto: "புகைப்படம் எடு",
      selectLanguage: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
      continue: "தொடரவும்",
      login: "உள்நுழைய",
      register: "பதிவு செய்ய",
      welcomeBack: "மீண்டும் வரவேற்கிறோம்!",
      loginToContinue: "தொடர உங்கள் கணக்கில் உள்நுழையவும்",
      mobileNumber: "மொபைல் எண்",
      createAccount: "புதிய கணக்கை உருவாக்கவும்",
      farmDetails: "தொடங்குவதற்கு உங்கள் விவரங்களை உள்ளிடவும்",
      name: "பெயர்",
      acresOfLand: "நிலத்தின் ஏக்கர்",
      areaOfLand: "நிலத்தின் பகுதி (எ.கா., கிராமம், நகரம்)",
      gallery: "கேலரி",
      analyzing: "பகுப்பாய்வு செய்கிறது...",
      healthy: "ஆரோக்கியமான",
      treatment: "சிகிச்சை",
      error: "பிழை",
      success: "வெற்றி",
      fillAllFields: "அனைத்து புலங்களையும் நிரப்பவும்.",
      invalidMobile: "சரியான 10 இலக்க மொபைல் எண்ணை உள்ளிடவும்.",
      accountCreated: "கணக்கு வெற்றிகரமாக உருவாக்கப்பட்டது! நீங்கள் இப்போது உள்நுழைந்துள்ளீர்கள்.",
      accountCreateFailed: "கணக்கை உருவாக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.",
      welcomeBackUser: "மீண்டும் வருக, {{name}}!",
      noAccountFound: "இந்த மொபைల్ எண்ணுடன் கணக்கு எதுவும் இல்லை. பதிவு செய்யவும்.",
      alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
      dontHaveAccount: "கணக்கு இல்லையா?",
      goBack: "பின் செல்",
      changeLanguage: "மொழியை மாற்று",
      smartFarmingAssistant: "உங்கள் έξυπൻ കൃഷി സഹായി",
      continueBoth: "Continue / தொடரவும்",
      permissionDenied: "அனுமதி மறுக்கப்பட்டது",
      locationPermission: "உள்ளூர் வானிலை மற்றும் ஆலோசனைகளை வழங்க இருப்பிட அணுகல் தேவை.",
      micPermission: "குரல் உதவியாளர் அம்சத்திற்கு மைக்ரோஃபோன் அணுகல் தேவை.",
      recommendationError: "பரிந்துரைகளைப் பெற முடியவில்லை",
      captureError: "படத்தைப் பிடிக்க முடியவில்லை",
      selectImageError: "படத்தைத் தேர்ந்தெடுக்க முடியவில்லை",
      analyzeError: "படத்தை பகுப்பாய்வு செய்ய முடியவில்லை",
      weatherError: "வானிலை தரவைப் பெற முடியவில்லை",
      voiceDemoError: "இந்த டெமோவில் குரல் గుర్తింపు கிடைக்கவில்லை",
      initError: "பயன்பாட்டைத் தொடங்குவதில் தோல்வி. தயவுசெய்து மீண்டும் தொடங்கவும்.",
    }
  },
  kn: {
    translation: {
      welcome: "ಅಗ್ರೋಎಐಗೆ ಸ್ವಾಗತ",
      cropRecommendation: "ಬೆಳೆ ಶಿಫಾರಸು",
      diseaseDetection: "ರೋಗ ಪತ್ತೆ",
      weather: "ಹವಾಮಾನ",
      takePhoto: "ಫೋಟೋ ತೆಗೆಯಿರಿ",
      selectLanguage: "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
      continue: "ಮುಂದುವರಿಸಿ",
      login: "ಲಾಗಿನ್ ಮಾಡಿ",
      register: "ನೋಂದಣಿ ಮಾಡಿ",
      welcomeBack: "ಮರಳಿ ಸ್ವಾಗತ!",
      loginToContinue: "ಮುಂದುವರಿಸಲು ನಿಮ್ಮ ಖಾತೆಗೆ ಲಾಗಿನ್ ಮಾಡಿ",
      mobileNumber: "ಮೊಬೈಲ್ ನಂಬರ್",
      createAccount: "ಹೊಸ ಖಾತೆಯನ್ನು ರಚಿಸಿ",
      farmDetails: "ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
      name: "ಹೆಸರು",
      acresOfLand: "ಭೂಮಿಯ ಎಕರೆ",
      areaOfLand: "ಭೂಮಿಯ ಪ್ರದೇಶ (ಉದಾ., ಗ್ರಾಮ, ನಗರ)",
      gallery: "ಗ್ಯಾಲರಿ",
      analyzing: "ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
      healthy: "ಆರೋಗ್ಯಕರ",
      treatment: "ಚಿಕಿತ್ಸೆ",
      error: "ದೋಷ",
      success: "ಯಶಸ್ಸು",
      fillAllFields: "ದಯವಿಟ್ಟು ಎಲ್ಲಾ ಕ್ಷೇತ್ರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ.",
      invalidMobile: "ದಯವಿಟ್ಟು ಮಾನ್ಯ 10-ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.",
      accountCreated: "ಖಾತೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ರಚಿಸಲಾಗಿದೆ! ನೀವು ಈಗ ಲಾಗ್ ಇನ್ ಆಗಿದ್ದೀರಿ.",
      accountCreateFailed: "ಖಾತೆಯನ್ನು ರಚಿಸಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
      welcomeBackUser: "ಮರಳಿ ಸ್ವಾಗತ, {{name}}!",
      noAccountFound: "ಈ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯೊಂದಿಗೆ ಯಾವುದೇ ಖಾತೆ ಕಂಡುಬಂದಿಲ್ಲ. ದಯವಿಟ್ಟು ನೋಂದಾಯಿಸಿ.",
      alreadyHaveAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?",
      dontHaveAccount: "ಖಾತೆ ಇಲ್ಲವೇ?",
      goBack: "ಹಿಂದಕ್ಕೆ ಹೋಗಿ",
      changeLanguage: "ಭಾಷೆ ಬದಲಾಯಿಸಿ",
      smartFarmingAssistant: "ನಿಮ್ಮ ಸ್ಮಾರ್ಟ್ ಫಾರ್ಮಿಂಗ್ ಸಹಾಯಕ",
      continueBoth: "Continue / ಮುಂದುವರಿಸಿ",
      permissionDenied: "ಅನುಮತಿ ನಿರಾಕರಿಸಲಾಗಿದೆ",
      locationPermission: "ಸ್ಥಳೀಯ ಹವಾಮಾನ ಮತ್ತು ಸಲಹೆಯನ್ನು ಒದಗಿಸಲು ಸ್ಥಳ ಪ್ರವೇಶದ ಅಗತ್ಯವಿದೆ.",
      micPermission: "ಧ್ವನಿ ಸಹಾಯಕ ವೈಶಿಷ್ಟ್ಯಕ್ಕಾಗಿ ಮೈಕ್ರೊಫೋನ್ ಪ್ರವೇಶದ ಅಗತ್ಯವಿದೆ.",
      recommendationError: "ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಲು ವಿಫಲವಾಗಿದೆ",
      captureError: "ಚಿತ್ರವನ್ನು ಸೆರೆಹಿಡಿಯಲು ವಿಫಲವಾಗಿದೆ",
      selectImageError: "ಚಿತ್ರವನ್ನು ಆಯ್ಕೆ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ",
      analyzeError: "ಚಿತ್ರವನ್ನು ವಿಶ್ಲೇಷಿಸಲು ವಿಫಲವಾಗಿದೆ",
      weatherError: "ಹವಾಮಾನ ಡೇಟಾವನ್ನು ತರಲು ವಿಫಲವಾಗಿದೆ",
      voiceDemoError: "ಈ ಡೆಮೊದಲ್ಲಿ ಧ್ವನಿ ಗುರುತಿಸುವಿಕೆ ಲಭ್ಯವಿಲ್ಲ",
      initError: "ಅಪ್ಲಿಕೇಶನ್ ಅನ್ನು ಪ್ರಾರಂಭಿಸಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮರುಪ್ರಾರಂಭಿಸಿ.",
    }
  },
  mr: {
    translation: {
      welcome: "ॲग्रोएआय मध्ये आपले स्वागत आहे",
      cropRecommendation: "पीक शिफारस",
      diseaseDetection: "रोग ओळख",
      weather: "हवामान",
      takePhoto: "फोटो घ्या",
      selectLanguage: "तुमची भाषा निवडा",
      continue: "पुढे जा",
      login: "लॉग इन करा",
      register: "नोंदणी करा",
      welcomeBack: "पुन्हा स्वागत आहे!",
      loginToContinue: "पुढे जाण्यासाठी तुमच्या खात्यात लॉग इन करा",
      mobileNumber: "मोबाईल नंबर",
      createAccount: "नवीन खाते तयार करा",
      farmDetails: "सुरुवात करण्यासाठी तुमचे तपशील प्रविष्ट करा",
      name: "नाव",
      acresOfLand: "जमिनीचे एकर",
      areaOfLand: "जमिनीचे क्षेत्र (उदा. गाव, शहर)",
      gallery: "गॅलरी",
      analyzing: "विश्लेषण करत आहे...",
      healthy: "निरोगी",
      treatment: "उपचार",
      error: "त्रुटी",
      success: "यशस्वी",
      fillAllFields: "कृपया सर्व फील्ड भरा.",
      invalidMobile: "कृपया वैध 10-अंकी मोबाइल नंबर प्रविष्ट करा.",
      accountCreated: "खाते यशस्वीरित्या तयार केले! आपण आता लॉग इन आहात.",
      accountCreateFailed: "खाते तयार करण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.",
      welcomeBackUser: "पुन्हा स्वागत आहे, {{name}}!",
      noAccountFound: "या मोबाइल नंबरसह कोणतेही खाते आढळले नाही. कृपया नोंदणी करा.",
      alreadyHaveAccount: "आधीपासूनच खाते आहे?",
      dontHaveAccount: "खाते नाही?",
      goBack: "मागे जा",
      changeLanguage: "भाषा बदला",
      smartFarmingAssistant: "तुमचा स्मार्ट शेती सहाय्यक",
      continueBoth: "Continue / पुढे जा",
      permissionDenied: "परवानगी नाकारली",
      locationPermission: "स्थानिक हवामान आणि सल्ला देण्यासाठी स्थान प्रवेश आवश्यक आहे.",
      micPermission: "व्हॉइस असिस्टंट वैशिष्ट्यासाठी मायक्रोफोन प्रवेश आवश्यक आहे.",
      recommendationError: "शिफारसी मिळविण्यात अयशस्वी",
      captureError: "प्रतिमा कॅप्चर करण्यात अयशस्वी",
      selectImageError: "प्रतिमा निवडण्यात अयशस्वी",
      analyzeError: "प्रतिमा विश्लेषण करण्यात अयशस्वी",
      weatherError: "हवामान डेटा आणण्यात अयशस्वी",
      voiceDemoError: "या डेमोमध्ये व्हॉइस रेकग्निशन उपलब्ध नाही",
      initError: "अ‍ॅप सुरू करण्यात अयशस्वी. कृपया पुन्हा सुरू करा.",
    }
  },
  bn: {
    translation: {
      welcome: "এগ্রোএআই-তে স্বাগতম",
      cropRecommendation: "ফসল সুপারিশ",
      diseaseDetection: "রোগ সনাক্তকরণ",
      weather: "আবহাওয়া",
      takePhoto: "ছবি তুলুন",
      selectLanguage: "আপনার ভাষা নির্বাচন করুন",
      continue: "চালিয়ে যান",
      login: "লগইন করুন",
      register: "নিবন্ধন করুন",
      welcomeBack: "আবারও স্বাগতম!",
      loginToContinue: "চালিয়ে যেতে আপনার অ্যাকাউন্টে লগইন করুন",
      mobileNumber: "মোবাইল নম্বর",
      createAccount: "একটি নতুন অ্যাকাউন্ট তৈরি করুন",
      farmDetails: "শুরু করতে আপনার বিবরণ লিখুন",
      name: "নাম",
      acresOfLand: "জমির একর",
      areaOfLand: "জমির এলাকা (যেমন, গ্রাম, শহর)",
      gallery: "গ্যালারি",
      analyzing: "বিশ্লেষণ করা হচ্ছে...",
      healthy: "স্বাস্থ্যকর",
      treatment: "চিকিৎসা",
      error: "ত্রুটি",
      success: "সাফল্য",
      fillAllFields: "অনুগ্রহ করে সমস্ত ক্ষেত্র পূরণ করুন।",
      invalidMobile: "অনুগ্রহ করে একটি বৈধ 10-সংখ্যার মোবাইল নম্বর লিখুন।",
      accountCreated: "অ্যাকাউন্ট সফলভাবে তৈরি করা হয়েছে! আপনি এখন লগ ইন করেছেন।",
      accountCreateFailed: "অ্যাকাউন্ট তৈরি করতে ব্যর্থ। অনুগ্রহ করে আবার চেষ্টা করুন।",
      welcomeBackUser: "আবারও স্বাগতম, {{name}}!",
      noAccountFound: "এই মোবাইল নম্বর দিয়ে কোনো অ্যাকাউন্ট পাওয়া যায়নি। অনুগ্রহ করে নিবন্ধন করুন।",
      alreadyHaveAccount: "ইতিমধ্যে একটি অ্যাকাউন্ট আছে?",
      dontHaveAccount: "অ্যাকাউন্ট নেই?",
      goBack: "ফিরে যান",
      changeLanguage: "ভাষা পরিবর্তন করুন",
      smartFarmingAssistant: "আপনার স্মার্ট ফার্মিং সহকারী",
      continueBoth: "Continue / চালিয়ে যান",
      permissionDenied: "অনুমতি প্রত্যাখ্যান করা হয়েছে",
      locationPermission: "স্থানীয় আবহাওয়া এবং পরামর্শ প্রদানের জন্য অবস্থান অ্যাক্সেস প্রয়োজন।",
      micPermission: "ভয়েস সহকারী বৈশিষ্ট্যের জন্য মাইক্রোফোন অ্যাক্সেস প্রয়োজন।",
      recommendationError: "সুপারিশ পেতে ব্যর্থ",
      captureError: "ছবি ক্যাপচার করতে ব্যর্থ",
      selectImageError: "ছবি নির্বাচন করতে ব্যর্থ",
      analyzeError: "ছবি বিশ্লেষণ করতে ব্যর্থ",
      weatherError: "আবহাওয়ার ডেটা আনতে ব্যর্থ",
      voiceDemoError: "এই ডেমোতে ভয়েস রিকগনিশন উপলব্ধ নেই",
      initError: "অ্যাপটি শুরু করতে ব্যর্থ। অনুগ্রহ করে পুনরায় চালু করুন।",
    }
  }
};

class LanguageService {
  constructor() {
    this.currentLanguage = 'en';
    this.initialized = false;
  }

  async initialize() {
    try {
      await i18next
        .use(initReactI18next)
        .init({
          resources,
          lng: this.currentLanguage,
          fallbackLng: 'en',
          interpolation: {
            escapeValue: false,
          },
        });

      this.initialized = true;
      console.log('Language service initialized');
    } catch (error) {
      console.error('Language service initialization error:', error);
      throw error;
    }
  }

  t = (key) => {
    if (!this.initialized) return key;
    return i18next.t(key);
  };

  async changeLanguage(languageCode) {
    try {
      await i18next.changeLanguage(languageCode);
      this.currentLanguage = languageCode;
    } catch (error) {
      console.error('Language change error:', error);
    }
  }

  getCurrentLanguage() {
    return this.currentLanguage;
  }

  getAvailableLanguages() {
    return [
      { code: 'en', name: 'English' },
      { code: 'hi', name: 'हिन्दी' },
      { code: 'te', name: 'తెలుగు' },
      { code: 'ta', name: 'தமிழ்' },
      { code: 'kn', name: 'ಕನ್ನಡ' },
      { code: 'mr', name: 'मराठी' },
      { code: 'bn', name: 'বাংলা' },
      // Add more languages here
    ];
  }
}

export default new LanguageService();